### ISSUE TITLE
Can I access the request header to extract a property and add it to defaultMeta?

### ISSUE THREAD

**Issue by kamzaa** [gremo/nest-winston#123]
I'm trying to access the http context essentially to retrieve a property and log it. 

How would I go about doing that?

**Comment by gremo** [comment]
Can't you write an [interceptor](https://docs.nestjs.com/interceptors), inject the logger, and then use the [`ExecutionContext`](https://docs.nestjs.com/fundamentals/execution-context) to the the request and properties that you need?

Is this what you mean?

**Comment by gremo** [comment]
Feel free to comment further. Closing it as it seems something related to NestJS framework.

**Comment by hjpotter92** [comment]
> Can't you write an [interceptor](https://docs.nestjs.com/interceptors), inject the logger, and then use the [`ExecutionContext`](https://docs.nestjs.com/fundamentals/execution-context) to get the request object and properties that you need (to log)?
> 
> Is this what you mean?

sorry to revive an old thread. I come from a lua background, could you provide a small sample on how the nest-winston logger could be injected with the execution context so that all `.log`/`.debug` calls to logger would receive the request meta data?

thanks for the amazing library. apologies if this is a stupid question.
