### ISSUE TITLE
structured logging (info objects)

### ISSUE THREAD

**Issue by fjgal** [gremo/nest-winston#165]
First things first, thanks for putting together this NestJS module.

We want to be able to use structured logging in our, not only json formatted output but also the ability to include application specific key-value pairs. This is something that Winston already supports, known as [info objects](https://github.com/winstonjs/winston#streams-objectmode-and-info-objects).

I could not find a way of achieving this in the current implementation of `nest-winston`. The limitation stems from the definition of `nestjs`'s `LoggerService` interface.

```javascript
export interface LoggerService {
    log(message: any, context?: string): any;
    error(message: any, trace?: string, context?: string): any;
    warn(message: any, context?: string): any;
    debug?(message: any, context?: string): any;
    verbose?(message: any, context?: string): any;
}
```

I would like to know if there is appetite for a contribution to extend the interface to allow for structured logging. The interface could look like:

```javascript
export interface StructuredLoggerService extends LoggerService {
  log(message: any, meta?: any): void;
  error(message: any, trace?: string, meta?: any): any;
  warn(message: any, meta?: any): any;
  debug?(message: any, meta?: any): any;
  verbose?(message: any, meta?: any): any;
}
```

the signature of the methods is compatible with the base interface. The implementation, `WinstonLogger`, could apply some logic to determine if the argument is a `context` string or a `meta` object and based on that delegate the logging to the underlaying `winston` logger instance.

Something on the lines of:

```javascript
  public log(message: any, meta?: any) {
    return this.logger.info(message, packFields(this.context, undefined, meta));
  }

function packFields(context?: string, trace?: string, meta?: any): any {
  let fields: any = {}
  if (typeof meta === 'string') {
    fields.context = meta;
  } else {
    fields.context = meta?.context || context
    fields = {...fields, ...meta, trace}
  }
  return fields
}
```

The app would use the logger like this:

```javascript
this.logger('this is a simple message`)
this.logger('this is a message that sets the context', 'context foo')
this.logger('this message attaches some key/value pairs', {foo: 'bar'})
```

If you think this is useful and the right approach I can submit a PR.

Thanks!

**Comment by gremo** [comment]
Hi @fjgal, first thanks for your contribution!

Just to be clear, we are talking about using this package as nest main logger (requests, errors, etc.).  I have a couple of question, as TypeScript is not my "main" language:

1. How you can change the signature (from` string` to `any`) and still get a correct implementation for the `LoggerService` interface?
2. Say that you make a PR with this changes. What happens if I decide, after using the info objects feature, to go back and use the "standard" implementation `WinstonLogger`? Should I change my code in order to make it work again?

**Comment by fjgal** [comment]
Hi @gremo , thanks for the quick response!

Disclaimer: TypeScript is not my main language either...

Yes, this package will be the nest main logger as well as the logger used by the application code.

> 1. How you can change the signature (from string to any) and still get a correct implementation for the LoggerService interface?

I believe this is working as a [function overload](https://www.typescriptlang.org/docs/handbook/functions.html#overloads). The TS compiler will validate the code against both signatures and one will match. At runtime, since the types are lost, the one and only implementation that `WinstonLogger` has will be called. The implementation of `WinstonLogger` has logic to treat both types or arguments (object or string).  I tested a prototype that uses it as main logger, with some application code that uses the standard `Logger` and some code that uses the new `StructuredLogger` and it behaves properly.

> 2. Say that you make a PR with this changes. What happens if I decide, after using the info objects feature, to go back and use the "standard" implementation WinstonLogger? Should I change my code in order to make it work again?

If your code uses the `StructuredLoggerService` and passes info objects and later on you decide to use the standard `LoggerService` interface you will have to make changes to your code since `info` objects won't be accepted by the TS compiler. It depends on what you are injecting into your services as logger service and how you are using it.

Also, to be clear, there would be only on implementation of `WinstonLogger` that implements the extended interface (`StructuredLoggerService`), so you would always have support for structured logging, unless you import an older version of `nest-winston`.

**Comment by gremo** [comment]
I see! So, if you have some spare time, go ahead and write a PR. I've been doing a major refactoring today, so clone/fork this repository again.

I think the PR would be quite "difficult" to accomplish. Some hints and thoughts:

1. Follow the contributing section (VS Code, linting, etc.)
2. No BC breaks if possible
3. Maybe it's a good idea to introduce a new class, as you said, `StructuredWinstonLogger`
4. This class should be used (opt-in) instead of the `WinstonLogger` default class
5. As a consequence, a new option should be introduced. For example, `nestLoggerImplementation: StructuredWinstonLogger` or `useStructuredLogger: true`
6. (Hard) maybe find a way to invalidating this new option, if I only use this module as a "standalone" logger and I don't want to replace the Nest logger.

Given the problems 3-6, maybe the solution would be to simply patch the `WinstonLogger` to support both string and objects.

**Comment by fjgal** [comment]
Sounds good, I'll try to find some time to work on it. Thanks!

**Comment by vorotech** [comment]
Hey folks,
This is my proposal #228  for structured logging (`meta` property) without breaking the Nest interface

cc: @fjgal @gremo

**Comment by fjgal** [comment]
@vorotech nice, that is a good compromise. Thanks for implementing it.

**Comment by fjgal** [comment]
we can close this issue, solved in https://github.com/gremo/nest-winston/pull/228
