### ISSUE TITLE
multiple Loggers??

### ISSUE THREAD

**Issue by hehehai** [gremo/nest-winston#214]
[how use multiple Loggers](https://github.com/winstonjs/winston#working-with-multiple-loggers-in-winston)

**Comment by gremo** [comment]
Hi @hehehai, as you probably already know this module isn't designed to work with multiple loggers. Because how Nest works, there is just one service/instance of the winston logger itself. I fear it will never be possible without rewrite this module from scratch.  I'll close this issue but feel free to work on a PR (without breaking changes).
