### ISSUE TITLE
Question: How to add meta data into logs when initialising this wrapper from bootstrap?

### ISSUE THREAD

**Issue by pkimtani** [gremo/nest-winston#397]
Hi!
First of all, thank you for making this amazing NestJS wrapper of Winston. It's really great and helpful.

I am currently trying to implement this wrapper in my project following the README guides. I am follow the [Replace NestJS logger (also bootstrap)](https://mybookings.easemytrip.com/).

I have a questoin about the usability:

- [ ] After I successfully replaced the NestJS logger, I can now simply `@Inject(logger) ...` in my CatsController, but with this approach I have now lost the winston capabilities of adding *meta* data to my log as the NestJS LoggerService interface defines, for ex: a log, as `error(message: any, trace?: string, context?: string): any;`, while winston uses LeveledLog which defines the same log as `(level: string, message: string, meta: any, callback: LogCallback): Logger;`. How can I replace NestJS logger with winston in a way that I can still utilise winston logger features like *meta* and etc.

Also, as a side note, I happen to observe the following behavior:
- [ ] According to the README, I have to add `Logger` to `providers` of `app.module.ts` and then `@Inject(Logger) ...` in any module should simply work (for ex: inside CatsController), but this doesn't seem to work as I had to also provide the `Logger` in `CatsModule`. Please correct me if I made some mistake. If not, it would be good to highlight this in README. Probably even drop the need of adding to `providers` of `app.module.ts`.

Thanks in advance!

**Comment by gremo** [comment]
Hello @pkimtani, thanks for asking, glad to help!

1. Yeah, I know, but replacing NestJS logger means to conform to the `LoggerService` and its methods. You can still pass an object instead of a string as logger `message` parameter. The object should have the `msg` property (the string)... anything else is metadata passed to Winston! `{ msg: 'A message', { foo: bar } }` Does this help?
2. Can you please explain better? Are you referring to "Replacing the Nest logger (also for bootstrapping)"?

**Comment by gremo** [comment]
Feel free to reply further if you need help!
