### ISSUE TITLE
How can we pass winston instance to nest-winston?

### ISSUE THREAD

**Issue by tt-farshid** [gremo/nest-winston#480]
I did not find a way to do that, I want to use some winston features.
We can provide winstonInstance to express-winston (similar library: https://github.com/bithavoc/express-winston), 
I am looking for such kind of property or anything else which can help me.

**Comment by gremo** [comment]
Hello, you mean you want to access the underlying winston instance? Can you provide an example of what you are trying to achive?

**Comment by GuillaumeDecMeetsMore** [comment]
Hello, I think I understand the request as I have the same need right now.

In my case, I would like to provide to the function `WinstonModule.createLogger({...})` an actual instance of Winston instead of the options needed to create a new one. So, this would mean:

```ts
WinstonModule.createLogger({
  winstonInstance: myWinstonInstance
})
```

This what express-winston linked above allows.

My main reason for that is the following: I need some way to access the Winston instance in order to update the `level` field. The goal is to allow to change the "minimum" level of logs at runtime in order to ease the debug in production. The easiest seems to create the Winston instance beforehand and keep it in a variable before giving it to WinstonModule, so that we can still interact on it.

What do you think ?
