### ISSUE TITLE
Log unhandled exceptions in readable form

### ISSUE THREAD

**Issue by Motard** [gremo/nest-winston#568]
There is a config option in Winston, called humanReadableUnhandledException. How can we use this in nest-winston?

**Comment by gremo** [comment]
You should able to do that. Types are imported directly from the winston package and module options are passed directly to the [createLogger()](https://github.com/winstonjs/winston#usage) function.

Since winston package is a peer dependency you should able to install the correct version that has the humanReadableUnhandledException option added!
